if(NOT DEFINED GRAPHICS_FILE OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "Graphics identity generation requires input and output paths")
endif()
file(SHA256 "${GRAPHICS_FILE}" graphics_digest)
set(header "#pragma once\nnamespace xkit { inline constexpr const char* GraphicsFacadeSha256 = \"${graphics_digest}\"; }\n")
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" previous)
    if(previous STREQUAL header)
        return()
    endif()
endif()
file(WRITE "${OUTPUT_FILE}" "${header}")
